steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']
- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'instances', 'create-with-container', 'instance1', '--subnet=pipeline-vpc-subnet', '--image-project=cos-cloud', '--zone=us-west1-a', '--container-image=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']